repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1  # Check for the latest version
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false  # Run on all tests, not just changed files
