services:
  api_service:
    build: api_service/
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: .
          ignore:
            - .venv/
        - action: rebuild
          path: uv.lock

