volumes:
  postgres_data:
services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_DB=${postgres_db}
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: backend/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network
    develop:
      watch:
        - action: sync
          path: .
          target: backend
          ignore:
            - backend/.venv/
        - action: rebuild
          path: ./backend/uv.lock
networks:
  my_network:
    driver: bridge

