[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.14.1",
    "environs>=14.1.0",
    "fastapi[standard]>=0.115.7",
    "httpx>=0.28.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.10", # TODO - Remove either psycopg2 or psycopg
    "psycopg[binary,pool]>=3.2.4",
    "pyjwt>=2.10.1",
    "sqlalchemy>=2.0.37",
]

[tool.ruff]
line-length=79
