[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.14.1",
    "bcrypt>=4.2.1",
    "environs>=14.1.0",
    "fastapi[standard]>=0.115.7",
    "psycopg2-binary>=2.9.10",
    "psycopg[binary,pool]>=3.2.4",
    "sqlalchemy>=2.0.37",
]

[tool.ruff]
line-length=79
